sonar.organization=josef10000
sonar.projectKey=traker
sonar.projectName=Traker
sonar.host.url=https://sonarcloud.io

# Source paths
sonar.sources=src,api
sonar.exclusions=**/node_modules/**,**/dist/**,**/public/**,**/coverage/**,**/*.spec.ts,**/*.test.ts,**/*.spec.tsx,**/*.test.tsx

# Encoding
sonar.sourceEncoding=UTF-8

# JavaScript / TypeScript coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info
